# Get user input
user_str = input("Enter a string: ")

print("\n--- 30 String Operations ---\n")

print(f"1. Original String: {user_str}")
print(f"2. Length: {len(user_str)}")
print(f"3. Uppercase: {user_str.upper()}")
print(f"4. Lowercase: {user_str.lower()}")
print(f"5. Title Case: {user_str.title()}")
print(f"6. Capitalized: {user_str.capitalize()}")
print(f"7. Swapcase: {user_str.swapcase()}")
print(f"8. Is Alpha: {user_str.isalpha()}")
print(f"9. Is Digit: {user_str.isdigit()}")
print(f"10. Is Alphanumeric: {user_str.isalnum()}")
print(f"11. Is Lower: {user_str.islower()}")
print(f"12. Is Upper: {user_str.isupper()}")
print(f"13. Is Space: {user_str.isspace()}")
print(f"14. Starts with 'a': {user_str.startswith('a')}")
print(f"15. Ends with 'z': {user_str.endswith('z')}")
print(f"16. Count of 'a': {user_str.count('a')}")
print(f"17. Find 'a': {user_str.find('a')}")
print(f"18. Replace 'a' with 'x': {user_str.replace('a', 'x')}")
print(f"19. Split by space: {user_str.split()}")
print(f"20. Join with '-': {'-'.join(user_str)}")
print(f"21. Strip spaces: {user_str.strip()}")
print(f"22. Left strip: {user_str.lstrip()}")
print(f"23. Right strip: {user_str.rstrip()}")
print(f"24. Center (width 20): {user_str.center(20, '*')}")
print(f"25. Left Justify (width 20): {user_str.ljust(20, '*')}")
print(f"26. Right Justify (width 20): {user_str.rjust(20, '*')}")
print(f"27. Encode to UTF-8: {user_str.encode('utf-8')}")
print(f"28. Index of first 'a': {(user_str.index('a') if 'a' in user_str else 'Not found')}")
print(f"29. Zfill (width 20): {user_str.zfill(20)}")
print(f"30. Reverse String: {user_str[::-1]}")
